FROM python:3.11-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Copia e instala dependencias Python
COPY requirements.txt .
RUN pip install --no-cache-dir  \
    --require-hashes \
    --only-binary=:all: \
    -r requirements.txt

# Copia el resto del código
COPY . .

EXPOSE 7001

CMD ["gunicorn", "-w", "2", "-b", "0.0.0.0:7001", "main:app"]